# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
# Just a comment to test something, will not be checked in and this is the only change.

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - sdk/iot/
    exclude:
    - sdk/iot/Azure.ResourceManager.IotFirmwareDefense
    - sdk/iot/ci.mgmt.yml

pr:
  branches:
    include:
    - main
  paths:
    include:
    - sdk/iot/
    exclude:
    - sdk/iot/Azure.ResourceManager.IotFirmwareDefense
    - sdk/iot/ci.mgmt.yml

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: iot
    BuildSnippets: false
    ArtifactName: packages
    Artifacts:
    - name: Azure.IoT.Hub.Service
      safeName: AzureIoTHubService

